language: go

go:
  - master

before_install:
    - go get github.com/mattn/goveralls
    - mkdir -p $HOME/.config/go-furnace

install: make get-deps

script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
